-- =====================================================
-- 06_load_final_tables.sql
-- Purpose: Load cleaned data into final relational tables
-- =====================================================